### ISSUE TITLE
BVTest1.ttf font uses incorrect script

### ISSUE THREAD

**Issue by SergeyMalkin** [athinkra/opentype-tests#1]
There are few issues:
- This font uses 'bamu' script tag in GSUB instead of correct 'bass' tag for Bassa Vah
- 'latn'script is defined in GSUB, but doesn't have any features associated with it.
  -Only 'latn' script is present in GPOS

All this makes this font very prone to fine implementation details of OpenType engines. You may consider fixing it (i.e. define all lookups under 'bass' tag) before you do further testing.

Interestingly, font in your Bassa Vah repository is very different: it specifies everything under 'DFLT' tag.

**Comment by andjc** [comment]
The bug has been fixed in version that hasn't been pushed to github yet

**Comment by andjc** [comment]
@SergeyMalkin,

Swapped in more recent versions of files that match feature file. I will probably strip out most latin script characters form font at some point in final font.

Font in Bassa Vah repo was an initial test file. Interestingly, defining everything under DFLT raised a few issues. 

At the moment I am uncertain if its best to use DFLT, bass or both, and if so which features yield the best results with which script. Part of the problem of working with what are still technically unsupported scripts on certain platforms.

**Comment by andjc** [comment]
See commit 3f16b58
